### ISSUE TITLE
Missing description from community CA build

### ISSUE THREAD

**Issue by samlhao** [czbiohub/covidtracker#1]
Hi team, very minor thing I noticed on the community build:
![image](https://user-images.githubusercontent.com/33997185/90405628-04d23500-e072-11ea-8368-b4f27e204c85.png)

Not sure if you're still looking to maintain this build, but considering it's still linked by the Nextstrain team, might be good to at least get rid of the default description.

Super minor, please ignore this if you're transitioning to making a public facing CA build on COVID Tracker.

**Comment by ttung** [comment]
We miss you, @samlhao!

**Comment by EmperorDali** [comment]
#1072 was supposed to fix this but didnt?

**Comment by ttung** [comment]
Fixed whenever https://github.com/nextstrain/ncov/pull/487 closes.
